name: UpdateNodes
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 18 * * *'

jobs:
  run-python-script:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'
      - run: pip install -r requirements
      - run: python main.py
